---
title: "Lab 8 - Final Project"
author: "NZ Gorham and Charlie Peterson"
date: "2026-07-30"
output: html_document
---

## Step 1
# Load in data here (and packages)
```{r}
baseballData <- read.csv("/Users/nzgor/Desktop/VSCode/Classes/EE 5373/Lab 8/baseball_hitting.csv")
library(MASS)
library(dplyr)
library(plotrix)
library(factoextra)
library(cluster)
library(ggplot2)
library(gifski)
library(gganimate)
```


## Step 2
# Do data filtering and backwards elimination process here
```{r}
baseball <-  baseballData %>% select(-Player.name, -stolen.base, -Caught.stealing) # removing unnecessary data from the original dataset
x <- na.omit(baseball)
sample <- sample(c(TRUE, FALSE), nrow(x), replace=TRUE, prob=c(0.7, 0.3))
train  <- x[sample, ]
test   <- x[!sample, ]
md <- lm(Games~., data = train)

# backwards elimination and graphs
stepAIC(md, direction = 'backward')
y <- stepAIC(md, direction = 'backward')
residuals <- resid(md)
plot(residuals)

# summaries 
summary(md)
summary(y)
```

## Step 3
# Map the Baseball Field with dots
https://search.r-project.org/CRAN/refmans/sportyR/html/geom_baseball.html - may help with setting up the baseball field
```{r}
base_map <- ggplot(county_info, aes(x = long, y = lat, group = group)) +
  geom_polygon(color = "black", fill = "white") +
  coord_quickmap(xlim = c(min(housing_data$long), max(housing_data$long)), ylim = c(min(housing_data$lat), max(housing_data$lat))) +
  theme_void()

base_map +
  geom_point(
    data = zip_summary,
    aes(x = long, y = lat, color = percent_error, size = median_price),
    inherit.aes = FALSE
  ) +
  scale_color_gradient(low = "green", high = "red", name = "Avg % error") +
  scale_size_continuous(name = "Median price") +
  labs(title = "Average percent error by zip code")
```
